version: '3'

services:
  tom-dev:
    image: moduo/devops:tom-2
    ports:
    - 8080
    labels:
    - "traefik.frontend.rule=Host:tom.dev.tomoud.nl"
    nathan-dev:
      image: moduo/devops:nathan-5
      ports:
      - 8080
      labels:
      - "traefik.frontend.rule=Host:nathan.dev.tomoud.nl"